# Generated by Django 5.1.2 on 2024-10-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(default='Unnamed Rule', max_length=255),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['name'], name='rules_rule_name_d986dc_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['created_at'], name='rules_rule_created_aec0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['is_active'], name='rules_rule_is_acti_2bafc6_idx'),
        ),
    ]
